language: python
python:
  - 3.6
matrix:  # python 3.7 workaround: https://github.com/travis-ci/travis-ci/issues/9815
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -e .
script:
  - pytest
