language: python
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
  - name: 3.6 public
    python: '3.6'
  - name: 3.6 private
    python: '3.6'
    env:
    - PRIVATE_ACCESS=1
    - secure: qvjB9qw/hgNcgwZB2BwmYue7f89Xn1uMgh0PQgPGZvB/ZmIkBeGJdEUByxXLGxOF27LuZa/+AMvr8P8S7OXAXCR7K9ty1IfazD1MbZJe57RbEPYZqzBTCK26KuMTVDjeBB/hCxji8z3TfKvVn7aJU4HNHtr7gT0CWppBWoebORsKomDUuvtkzRtekLs/WUgJigNemmFR/u90BoP94eYMzY4ClPzwL1o0a+PTEX9zA74qzeAOWiUEs4mb7bUSQ3EL9eSkEg8y3jiUpfj0OcwQvGeslSKjC0gi3rJnfyfNdsBua4Sllo0vxDDrPaITdIAtvPY13LYhguMQ8GJwFKS+/WPkBHgDtSEkUxMuFFeKRU3xfQtqc8Cbu1+HYnUnTDS6XBK2gPJlWEK8uMbzo6rMLmrFv62GEQCWI9mY4ZfKjHK4q1Xj45Xa1QBeyZDuWgUttMXfehmya+1ABl3gN964FFtNTj2dsKkNv8VtMRzC/sxHQWiuzvfpGQLWJ+eWvcWMPROebD1c9ZtDbrL48EkDvD1Qi4f1cTdY7eXXVNT41B7ZyOAJiQqR9VhWVnOipIlMXpJl2ixcvSxeGaBQ1EqOzBb5THDvQk3SgbnNL0DzP7hiOwXA+Mn5tmf/7t2RbFehLaDUjRU+LdYzWzuohnOkV6/B94UNQ//zXJddYWjkjY4=
    - secure: lpgw+9QYuT12E61y1wqdf9ypa2liMFNkVPFKtlTl9X8Xy7CBmINWi5WHBpFIPHr1GiIwN+Ht0S5Ua3hBdlAqcYQOpKIizqlMv/NrEK0UzwSmVuEM+NejTW8jjdOQ4spNY8xKxwd2VERHYfjET0keo6VlTAwFcFUHQuSPa/gYE5QdwvCp8WskyWdmWKovciCl33uZIWqPMHN+P/ESnzclQ+rPie3kteMpD4xzXjvn/nGQ0gZqRpJAxzu5Sg1gkM9T+DeCP0mokjQOnfgkwGzr7n8cEWVK1jy1VoDIG1w75alfmoCuGULvICBXPHj4nw8FLR2jQkfUBo5NJGV9KDqFSjGu3wTbEsEigXLKT6NrwJJxhXhN6x/P3flIB3T2w0nW2+SXokwENe9gBYjfoVnBq+vNPsZOie+5r04Xr7NqatbNlJ4erE6I1pHq/kSi26XMzKHvQ1YVmXPYsBzbjzJTDWmEYZD24FcG7lSj/PvEdyQ7yqbVdBq96tbwJXI42ARPefT24KkPjC5IHasJHq1tJ5cm/gOL3o6xdc5xvliVpIB7ruJVg4aHWPWKk6NixEO4iEg+Jv/mYRzgK5aMdNLdc4xXUv9GBirCOJUdvJRhyGFJfac4p6KHIJdp+p3C82+S5QHSZWw6RnX/y3OOX1zG+4HQwrCqIF3OK0n7bUGXHAs=
    - AWS_DEFAULT_REGION=us-east-1
before_install:
- pip install --upgrade pip
install:
- pip install .
script:
- if [ "$PRIVATE_ACCESS" = 1 ]; then pytest --skip-memory-intense; fi
- if [ "$PRIVATE_ACCESS" != 1 ]; then pytest --skip-private --skip-memory-intense; fi
