language: python
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
  - name: 3.6 public
    python: '3.6'
  - name: 3.6 private
    python: '3.6'
    env:
    - PRIVATE_ACCESS=1
    - secure: qvjB9qw/hgNcgwZB2BwmYue7f89Xn1uMgh0PQgPGZvB/ZmIkBeGJdEUByxXLGxOF27LuZa/+AMvr8P8S7OXAXCR7K9ty1IfazD1MbZJe57RbEPYZqzBTCK26KuMTVDjeBB/hCxji8z3TfKvVn7aJU4HNHtr7gT0CWppBWoebORsKomDUuvtkzRtekLs/WUgJigNemmFR/u90BoP94eYMzY4ClPzwL1o0a+PTEX9zA74qzeAOWiUEs4mb7bUSQ3EL9eSkEg8y3jiUpfj0OcwQvGeslSKjC0gi3rJnfyfNdsBua4Sllo0vxDDrPaITdIAtvPY13LYhguMQ8GJwFKS+/WPkBHgDtSEkUxMuFFeKRU3xfQtqc8Cbu1+HYnUnTDS6XBK2gPJlWEK8uMbzo6rMLmrFv62GEQCWI9mY4ZfKjHK4q1Xj45Xa1QBeyZDuWgUttMXfehmya+1ABl3gN964FFtNTj2dsKkNv8VtMRzC/sxHQWiuzvfpGQLWJ+eWvcWMPROebD1c9ZtDbrL48EkDvD1Qi4f1cTdY7eXXVNT41B7ZyOAJiQqR9VhWVnOipIlMXpJl2ixcvSxeGaBQ1EqOzBb5THDvQk3SgbnNL0DzP7hiOwXA+Mn5tmf/7t2RbFehLaDUjRU+LdYzWzuohnOkV6/B94UNQ//zXJddYWjkjY4=
    - secure: lpgw+9QYuT12E61y1wqdf9ypa2liMFNkVPFKtlTl9X8Xy7CBmINWi5WHBpFIPHr1GiIwN+Ht0S5Ua3hBdlAqcYQOpKIizqlMv/NrEK0UzwSmVuEM+NejTW8jjdOQ4spNY8xKxwd2VERHYfjET0keo6VlTAwFcFUHQuSPa/gYE5QdwvCp8WskyWdmWKovciCl33uZIWqPMHN+P/ESnzclQ+rPie3kteMpD4xzXjvn/nGQ0gZqRpJAxzu5Sg1gkM9T+DeCP0mokjQOnfgkwGzr7n8cEWVK1jy1VoDIG1w75alfmoCuGULvICBXPHj4nw8FLR2jQkfUBo5NJGV9KDqFSjGu3wTbEsEigXLKT6NrwJJxhXhN6x/P3flIB3T2w0nW2+SXokwENe9gBYjfoVnBq+vNPsZOie+5r04Xr7NqatbNlJ4erE6I1pHq/kSi26XMzKHvQ1YVmXPYsBzbjzJTDWmEYZD24FcG7lSj/PvEdyQ7yqbVdBq96tbwJXI42ARPefT24KkPjC5IHasJHq1tJ5cm/gOL3o6xdc5xvliVpIB7ruJVg4aHWPWKk6NixEO4iEg+Jv/mYRzgK5aMdNLdc4xXUv9GBirCOJUdvJRhyGFJfac4p6KHIJdp+p3C82+S5QHSZWw6RnX/y3OOX1zG+4HQwrCqIF3OK0n7bUGXHAs=
    - AWS_DEFAULT_REGION=us-east-1
before_install:
- pip install --upgrade pip
install:
- pip install .
script:
- if [ "$PRIVATE_ACCESS" = 1 ]; then pytest --skip-memory-intense; fi
- if [ "$PRIVATE_ACCESS" != 1 ]; then pytest --skip-private --skip-memory-intense;
  fi
env:
  global:
  - secure: IULfcDRlV6Q3G04BfPxNpwyj15cr0LwtqJxSayQrLctdE1Ss6ji8bCDiVs7bGQbsXWkNRL2T6WSFMTqgLVHKBcA0BVKQDFqPZM78uwMaz4VllSBlIPh2B8U5zsmNDe+KZ/eZ/mnPSJfy+8UIYIobtLgPWAZKK+EUVQdaxATPiL3PzRuRikuhvzwgtGUOUy899NuHgolU2br4VZa7w1FYYx6TIxBDCDFG17PS5VBu91JsSeIStmnN0man2kxWfe4TdJzhIz3OrdOstL44R4QXOYj3Ppa8k0FQ8J11VljvWKktmeoJzC4fsuRMM0dZuyvmITWoN3C9AcdJQDNxaHg+0eyxjyDG3/2yOxuO5cGJjCBDk80aPfd7uk7wStUFRdIVQGBxz0D8v5Zgey9BCYC/wRpzS3Q17yOxPqxjLTg89bGsJCSKhZYc/8RdfsdlZvf8Qb5qYpcloxMxPCFZW9xDrAM8TKiCKyQHiRBeEX6M8nBtJwGg8L2LXw9lXGyv7tREeIeucVDjMILOMWuGnIveh+w4BOwg8CkVP7eDf9GjQeLWBaA5P+9rkwPjkmoKTk+xlqT0u+BggHoWE2opi4pt++X1xtwftEdkIRuBb6iAIX+hErBT8ze2gkeMig72ZQAfLbANbuunbiNW2AmJh2fB2g5kaklYK+x0ywPw6xuDftg=
  - secure: kgYmj7LhHuxSU6mAcpS6sXU+jMZp9VDaMl0GciNXw4k7IcBhdfGGizfJB2kalUhkLyjDIRfTAZ8Po5FOw7zbwPWR6pZguRV8AlULOvt99Yo+rGF22ZjjS9UpOVaPlpIDDNpyebhiXqJTxQCe+aXmZM5NZWbR3X0ljVK4FW9nUQjJtwHXiYYVooYUVIL0YHJqbeu04uVRHVURxl9ZtOWRPSpSSt7LkfYCstgRnknRCtvcfbgzWHhCAq3CyjbJLCjslyD/iHm90ALWJuOJ4sELh9EvzZagm7VUfSMjnJSI3dMoYhQxpJnmFgYgI2bQQfdhM+39cmzGptq1PkBdw+aUajT7G3IYYeVkIg3FAKBkjdtTI3Jv0D+WqGYoKgKRXnKNtd4/1NJoDsTtEwVURwnht8VbJuZ1OGPfuTtK4mf5xd/lOToRmge3kuuKkGNw9hXIdd+rzBFO2S/EijcrU5XA8SHy5iASRz7mUc0e/MYc4Tq9os724zSEXqAu1oCnQd/zjMJYV5Lqtdvlup12aQRarsRS5ZRg1YsKk2q1ApV2KucAAm7U106DQMNZLTw28ameLOs6UwnMiY1RVfN3tAr/W8Hov9y6BenLxc1zsYKmo0Fwvhq1mG0Uz++/On3pI+hWNHa3jCTVGVY1C45a4UivnaRg2HgPGvftRIwDrtIvThw=
